# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Twitter-clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Twitter-clone
pod 'SnapKit'
pod 'Then'
pod 'Alamofire'
pod 'Kingfisher'

end
